# Generated by Django 4.1.5 on 2023-01-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_terminal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_name', to='api.client'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='location_name', to='api.location'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_name', to='api.model'),
        ),
    ]
