# Generated by Django 4.1.5 on 2023-01-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_terminal_client_alter_terminal_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=63)),
                ('puk', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='terminal',
            name='chip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chip'),
        ),
    ]
