# Generated by Django 4.1.5 on 2023-01-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_terminal_chip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Acquirer',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='client',
            new_name='acquirer',
        ),
    ]
