# Generated by Django 4.1.5 on 2023-01-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_terminal_id_pos2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.DeleteModel(
            name='Chip',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='acquirer',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='id_pos2000',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='location',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='model',
        ),
        migrations.AddField(
            model_name='terminal',
            name='acquirer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.acquirer'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='location_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.location'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model'),
        ),
    ]
