# Generated by Django 4.1.5 on 2023-01-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_terminal_status_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='acquirer_id',
            new_name='acquirer',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='status_id',
            new_name='status',
        ),
    ]
